server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: password
  redis:
    host: localhost
    port: 6379
    password: pass1234
    database: 0
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
#redisson:
#  address: redis://localhost:6379
#  password: pass1234